In [1]:
import numpy as np 

from sklearn.preprocessing import MinMaxScaler

data = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])
 
scaler = MinMaxScaler()

scaler.fit(data)

data


array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [2]:
print('min values: ', scaler.data_min_, 'max values: ', scaler.data_max_) 

min values:  [-1.  2.] max values:  [ 1. 18.]


In [3]:
scaler.transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [4]:
data

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [5]:
MinMaxScaler().fit_transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [6]:
data2 = np.array([[0, 4], [-1.5, 20]])
data2

array([[ 0. ,  4. ],
       [-1.5, 20. ]])

In [7]:
scaler.transform(data2)

array([[ 0.5  ,  0.125],
       [-0.25 ,  1.125]])

In [8]:
scaler.fit_transform(data2)

array([[1., 0.],
       [0., 1.]])